### ISSUE TITLE
No LoadTimeWeaver available

### ISSUE THREAD

**Issue by mrj365** [subes/invesdwin-nowicket#2] opened 2016-09-14 17:52 UTC
I am running spring boot 1.3, on Jboss EAP 7 inside eclipse. When I run it, I get the following exception:

No LoadTimeWeaver available

I configured the spring boot application as described in your readme

```
13:50:20,728 ERROR [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 67) Application startup failed: java.lang.IllegalStateException: No LoadTimeWeaver available
	at org.springframework.context.weaving.AspectJWeavingEnabler.enableAspectJWeaving(AspectJWeavingEnabler.java:80)
	at org.springframework.context.weaving.AspectJWeavingEnabler.postProcessBeanFactory(AspectJWeavingEnabler.java:71)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:174)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:129)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:175)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:184)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
```

**Comment by subes** [comment] 2016-09-14 18:05
A few questions I have:
1. Have you tried specifying the java agent explicitly? Though dunno if this works at all with JBoss's classloading semantics; maybe you should use the transforming classloader in your spring boot app like described here: https://github.com/spring-projects/spring-boot/issues/739
2. does the invesdwin-instrument call lead to any exceptions? I wonder that it simply works on JBoss or any other application servers.
3. Can you provide a sample project that I can checkout and reproduce the problem locally?

**Comment by subes** [comment] 2016-09-14 18:30
Also you are not required to use spring-boot with invesdwin-nowicket, you could as well just go with EJB or whatever is normally used in JBoss.

**Comment by subes** [comment] 2016-09-24 11:35
Closing since getting no additional info from submitter and problem seems not to be related to nowicket, but instead is a deployment issue with spring-boot. Please reopen if I am wrong.

**Closed by subes** 2016-09-24 11:35 UTC
